---
kind: pipeline
name: build


# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
# https://cogarius.medium.com/1-3-complete-guide-to-ci-cd-pipelines-with-drone-io-a53daaf28cf6
globals:
  version: 
    - &tor_version TOR_VERSION=0.4.7.12
    - &docker_tags 0.4.7.12
  repo: &repo svengo/tor

  settings: &docker_creds
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password

  settings: &telegram_creds
    token:
      from_secret: telegram_token
    to: 
      from_secret: telegram_username
  

# https://discourse.drone.io/t/best-practice-for-building-multiple-branch-triggers-with-multiple-tags/8006/2
steps:
- name: publish release image
  image: plugins/docker
  pull: if-not-exists

  # https://plugins.drone.io/plugins/docker
  # https://docs.drone.io/plugins/popular/docker/
  settings:
    <<: *docker_creds
    build_args:
      - *tor_version
    repo: *repo
    tags: 
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
      - *docker_tags
    purge: false
    dry_run: false
    force_tag: true
  when:
    branch:
      - main

- name: publish development image
  image: plugins/docker
  pull: if-not-exists

  # https://plugins.drone.io/plugins/docker
  # https://docs.drone.io/plugins/popular/docker/
  settings:
    <<: *docker_creds
    build_args:
      - *tor_version
    repo: *repo
    tags: 
      - ${DRONE_BRANCH/\//-}
    purge: false
    dry_run: false
    force_tag: true
  when:
    branch:
      exclude:
        # https://docs.drone.io/pipeline/macstadium/syntax/conditions/
        - main

# https://stanislas.blog/2018/08/setup-telegram-bot-for-drone-ci-cd-builds/
- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    <<: *telegram_creds
    format: markdown
    message: >
      {{#success build.status}}
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.

      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```

      🌐 {{ build.link }}
      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.

      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```

      🌐 {{ build.link }}
      {{/success}}
  trigger:
    status:
      - success
      - failure

trigger:
  event:
    - push
