#!/bin/bash

#
# http://windsock.io/automated-docker-image-builds-with-multiple-tags/
# https://github.com/docker/hub-feedback/issues/341#issuecomment-248722131
# 

set -e

# Tag and push image for each additional tag
for tag in {0.3.0.10,latest}; do
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${tag}
  docker push ${DOCKER_REPO}:${tag}
done
