name: Cleanup build cache

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # Daily at 1 AM UTC
    
jobs:
  cleanup:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
        run: |
          echo "Deleting caches..."
          gh cache delete --all --succeed-on-no-caches --repo "${{ github.repository }}"
          echo "Done"
